let arr = [1, 2, 3, 4, 5, 6]
let arr1 = arr.slice(1, 2)
console.log(arr1)
let arr2 = arr.slice(2)
console.log(arr2)
let arr3 = arr.slice()
console.log(arr3)
let arr4 = arr.slice(-1)
console.log(arr4)
let arr5 = arr.slice(-1, 3)
console.log(arr5)
let arr6 = arr.slice(-1, -3)
console.log(arr6)
let arr7 = arr.slice(-3, -1)
console.log(arr7)
let arr8 = arr.slice(3, 123)
console.log(arr8)
